# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    http_client:
        default_options:
            headers:
                'Content-Type': 'application/ld+json'

                'x-api-token': 'adf91a62b2e2e85fe33524685746903902cdcdfc795d8ea9c516ca3b8b3e1c71f69fe2ae2c0d2271e8da951f2fc397724bfdbe5290685cd9e4b21a27'
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
